Fix type for singular problems
Without the change to trust_region.jl, the new test would trigger:
ERROR: MethodError: `wnorm` has no method matching wnorm(::Array{Float32,1}, ::Array{Float64,1})